

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7111:8080" 
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__dbms: Host=host.docker.internal;Port=5432;Database=skillsheet;Username=postgres;Password=Hardik@211
    depends_on:
      - db
    volumes:
      - ./SkillSheetAPI/wwwroot/uploads:/app/wwwroot/uploads

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hardik@211
      POSTGRES_DB: skillsheet
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  frontend:
    build:
      context: ../skill-sheet
      dockerfile: Dockerfile
    ports:
      - "3000:80" 
    volumes:
      - ../skill-sheet:/app
    environment:
      NODE_ENV: development
    depends_on:
      - api

volumes:
  postgres-data: