using Microsoft.AspNetCore.Mvc;
using SkillSheetAPI.Services.Interfaces;
using SkillSheetAPI.Services.Services;
using System.Threading.Tasks;

namespace SkillSheetAPI.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class PDFController : ControllerBase
    {
        private readonly IPdfService _pdfService;

        public PDFController(IPdfService pdfService)
        {
            _pdfService = pdfService;
        }

        [HttpGet("GeneratePDF")]
        public async Task<IActionResult> GeneratePDF()
        {
            var title = "Sample PDF";
            var content = "This is a sample PDF generated by iTextSharp.";

            var pdfBytes = await _pdfService.CreatePDFAsync(title, content);

            return File(pdfBytes, "application/pdf", "sample.pdf");
        }
    }
}